/**
 * Auth Action Types
 */
export const AUTO_LOGIN_ERROR = 'AUTH/AUTO_LOGIN_ERROR'
export const SIGNUP_REQUEST = 'AUTH/SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'AUTH/SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'AUTH/SIGNUP_ERROR'
export const LOGIN_REQUEST = 'AUTH/LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS'
export const LOGIN_ERROR = 'AUTH/LOGIN_ERROR'
export const FETCH_PROFILE_REQUEST = 'AUTH/FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'AUTH/FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_ERROR = 'AUTH/FETCH_PROFILE_ERROR'

export const VERIFY_REQUEST = 'AUTH/VERIFY_REQUEST'
export const VERIFY_SUCCESS = 'AUTH/VERIFY_SUCCESS'
export const VERIFY_ERROR = 'AUTH/VERIFY_ERROR'

export const UPDATE_PROFILE_REQUEST = 'AUTH/UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'AUTH/UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'AUTH/UPDATE_PROFILE_ERROR'

export const UPDATE_PASSWORD_REQUEST = 'AUTH/UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_SUCCESS = 'AUTH/UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'AUTH/UPDATE_PASSWORD_ERROR'
export const LOGOUT = 'AUTH/LOGOUT'

/** GLOBAL **/
export const SET_GLOBAL_INFORMATION = 'GLOBAL/INFORMATOIN'
/**
 * Nav Action Types
 */
export const SET_NAVIGATION = 'SET_NAVIGATION'
export const REFRESH_NAVIGATION_WITH_WORKSPACE =
  'REFRESH_NAVIGATION_WITH_WORKSPACE'
export const REFRESH_NAVIGATION_WITH_WORKSPACES =
  'REFRESH_NAVIGATION_WITH_WORKSPACES'
export const REFRESH_NAVIGATION_WITH_NO_WORKSPACE =
  'REFRESH_NAVIGATION_WITH_NO_WORKSPACE'

/** WORK SPACES **/
export const SET_WORKSPACE = 'SET_WORKSPACE'
export const LOAD_WORKSPACE = 'LOAD_WORKSPACE'

export const WORKSPACES_FETCH_REQUEST = 'WORKSPACES/FETCH_REQUEST'
export const WORKSPACES_FETCH_SUCCESS = 'WORKSPACES/FETCH_SUCCESS'
export const WORKSPACES_FETCH_ERROR = 'WORKSPACES/FETCH_ERROR'

export const WORKSPACES_AUTO_LOAD_REQUEST = 'WORKSPACES/AUTO_LOAD_REQUEST'
export const WORKSPACES_AUTO_LOAD_SUCCESS = 'WORKSPACES/AUTO_LOAD_SUCCESS'
export const WORKSPACES_AUTO_LOAD_ERROR = 'WORKSPACES/AUTO_LOAD_ERROR'

export const WORKSPACES_FETCH_SINGLE_REQUEST = 'WORKSPACES/FETCH_SINGLE_REQUEST'
export const WORKSPACES_FETCH_SINGLE_SUCCESS = 'WORKSPACES/FETCH_SINGLE_SUCCESS'
export const WORKSPACES_FETCH_SINGLE_ERROR = 'WORKSPACES/FETCH_SINGLE_ERROR'

export const WORKSPACES_ADD_REQUEST = 'WORKSPACES/ADD_REQUEST'
export const WORKSPACES_ADD_SUCCESS = 'WORKSPACES/ADD_SUCCESS'
export const WORKSPACES_ADD_ERROR = 'WORKSPACES/ADD_ERROR'
export const WORKSPACES_UPDATE_REQUEST = 'WORKSPACES/UPDATE_REQUEST'
export const WORKSPACES_UPDATE_SUCCESS = 'WORKSPACES/UPDATE_SUCCESS'
export const WORKSPACES_UPDATE_ERROR = 'WORKSPACES/UPDATE_ERROR'
export const WORKSPACES_REMOVE_REQUEST = 'WORKSPACES/REMOVE_REQUEST'
export const WORKSPACES_REMOVE_SUCCESS = 'WORKSPACES/REMOVE_SUCCESS'
export const WORKSPACES_REMOVE_ERROR = 'WORKSPACES/REMOVE_ERROR'

export const WORKSPACES_DEPLOY_REQUEST = 'WORKSPACES/DEPLOY_REQUEST'
export const WORKSPACES_DEPLOY_SUCCESS = 'WORKSPACES/DEPLOY_SUCCESS'
export const WORKSPACES_DEPLOY_ERROR = 'WORKSPACES/DEPLOY_ERROR'

export const DEPLOY_LOAD_REQUEST = 'DEPLOYS/LOAD_REQUEST'
export const DEPLOY_LOAD_SUCCESS = 'DEPLOYS/LOAD_SUCCESS'
export const DEPLOY_LOAD_ERROR = 'DEPLOYS/LOAD_ERROR'

export const DEPLOY_CANCEL_REQUEST = 'DEPLOYS/CANCEL_REQUEST'
export const DEPLOY_CANCEL_SUCCESS = 'DEPLOYS/CANCEL_SUCCESS'
export const DEPLOY_CANCEL_ERROR = 'DEPLOYS/CANCEL_ERROR'
/** Intents **/
export const SET_INTENT = 'SET_INTENT'
export const INTENTS_LOAD_ERROR = 'INTENTS/LOAD_ERROR'
export const INTENTS_LOAD_REQUEST = 'INTENTS/LOAD_REQUEST'
export const INTENTS_LOAD_SUCCESS = 'INTENTS/LOAD_SUCCESS'
export const INTENTS_ADD_REQUEST = 'INTENTS/ADD_REQUEST'
export const INTENTS_ADD_SUCCESS = 'INTENTS/ADD_SUCCESS'
export const INTENTS_ADD_ERROR = 'INTENTS/ADD_ERROR'
export const INTENTS_REMOVE_REQUEST = 'INTENTS/REMOVE_REQUEST'
export const INTENTS_REMOVE_SUCCESS = 'INTENTS/REMOVE_SUCCESS'
export const INTENTS_REMOVE_ERROR = 'INTENTS/REMOVE_ERROR'
export const INTENTS_UPDATE_REQUEST = 'INTENTS/UPDATE_REQUEST'
export const INTENTS_UPDATE_SUCCESS = 'INTENTS/UPDATE_SUCCESS'
export const INTENTS_UPDATE_ERROR = 'INTENTS/UPDATE_ERROR'
export const INTENTS_FETCH_SINGLE_REQUEST = 'INTENTS/FETCH_SINGLE_REQUEST'
export const INTENTS_FETCH_SINGLE_SUCCESS = 'INTENTS/FETCH_SINGLE_SUCCESS'
export const INTENTS_FETCH_SINGLE_ERROR = 'INTENTS/FETCH_SINGLE_ERROR'

/** Entities **/
export const SET_ENTITY = 'SET_ENTITY'

export const ENTITY_LOAD_REQUESTED = 'ENTITY_LOAD_REQUESTED'
export const ENTITY_LOAD_SUCCEDED = 'ENTITY_LOAD_SUCCEDED'
export const ENTITY_LOAD_ERROR = 'ENTITY_LOAD_ERROR'

export const ENTITY_SAVE_REQUESTED = 'ENTITY_SAVE_REQUESTED'
export const ENTITY_SAVE_SUCCEDED = 'ENTITY_SAVE_SUCCEDED'
export const ENTITY_SAVE_ERROR = 'ENTITY_SAVE_ERROR'

/** FAQs **/
export const FAQ_LOAD_REQUESTED = 'FAQ_LOAD_REQUESTED'
export const FAQ_LOAD_SUCCEDED = 'FAQ_LOAD_SUCCEDED'
export const FAQ_LOAD_ERROR = 'FAQ_LOAD_ERROR'
export const FAQ_PRODUCT_UPDATE_REQUESTED = 'FAQ_PRODUCT_UPDATE_REQUESTED'
export const FAQ_PRODUCT_UPDATE_SUCCEDED = 'FAQ_PRODUCT_UPDATE_SUCCEDED'
export const FAQ_PRODUCT_UPDATE_ERROR = 'FAQ_PRODUCT_UPDATE_ERROR'
export const FAQ_QUESTION_UPDATE_REQUESTED = 'FAQ_QUESTION_UPDATE_REQUESTED'
export const FAQ_QUESTION_UPDATE_SUCCEDED = 'FAQ_QUESTION_UPDATE_SUCCEDED'
export const FAQ_QUESTION_UPDATE_ERROR = 'FAQ_QUESTION_UPDATE_ERROR'
export const FAQ_QUESTION_DELETE_REQUESTED = 'FAQ_QUESTION_DELETE_REQUESTED'
export const FAQ_QUESTION_DELETE_SUCCEDED = 'FAQ_QUESTION_DELETE_SUCCEDED'
export const FAQ_QUESTION_DELETE_ERROR = 'FAQ_QUESTION_DELETE_ERROR'

/** CHANNEL **/
export const CHANNEL_LOAD_REQUESTED = 'CHANNEL/LOAD_REQUESTED'
export const CHANNEL_LOAD_SUCCEDED = 'CHANNEL/LOAD_SUCCEDED'
export const CHANNEL_LOAD_ERROR = 'CHANNEL/LOAD_ERROR'
export const CHANNEL_UPDATE_REQUESTED = 'CHANNEL/UPDATE_REQUESTED'
export const CHANNEL_UPDATE_SUCCEDED = 'CHANNEL/UPDATE_SUCCEDED'
export const CHANNEL_UPDATE_ERROR = 'CHANNEL/UPDATE_ERROR'

/** TEST BOT **/
export const TESTBOT_QUERY_REQUEST = 'TESTBOT/QUERY_REQUEST'
export const TESTBOT_QUERY_SUCCESS = 'TESTBOT/QUERY_SUCCESS'
export const TESTBOT_QUERY_ERROR = 'TESTBOT/QUERY_ERROR'
export const TESTBOT_SHOW = 'TESTBOT/SHOW'
export const TESTBOT_HIDE = 'TESTBOT/HIDE'
export const TESTBOT_WITHFLOW_QUERY_REQUEST = 'TESTBOT/WITHFLOW_QUERY_REQUEST'
export const TESTBOT_WITHFLOW_QUERY_SUCCESS = 'TESTBOT/WITHFLOW_QUERY_SUCCESS'
export const TESTBOT_WITHFLOW_QUERY_ERROR = 'TESTBOT/WITHFLOW_QUERY_ERROR'

/** Small Talk **/
export const SMALL_TALK_LOAD_REQUESTED = 'SMALL_TALK_LOAD_REQUESTED'
export const SMALL_TALK_LOAD_SUCCEEDED = 'SMALL_TALK_LOAD_SUCCEEDED'
export const SMALL_TALK_LOAD_ERROR = 'SMALL_TALK_LOAD_ERROR'
export const SMALL_TALK_CATEGORY_UPDATE_REQUESTED =
  'SMALL_TALK_CATEGORY_UPDATE_REQUESTED'
export const SMALL_TALK_CATEGORY_UPDATE_SUCCEEDED =
  'SMALL_TALK_CATEGORY_UPDATE_SUCCEEDED'
export const SMALL_TALK_CATEGORY_UPDATE_ERROR =
  'SMALL_TALK_CATEGORY_UPDATE_ERROR'
export const SMALL_TALK_UPDATE_REQUESTED = 'SMALL_TALK_UPDATE_REQUESTED'
export const SMALL_TALK_UPDATE_SUCCEEDED = 'SMALL_TALK_UPDATE_SUCCEEDED'
export const SMALL_TALK_UPDATE_ERROR = 'SMALL_TALK_UPDATE_ERROR'
export const SMALL_TALK_DELETE_REQUESTED = 'SMALL_TALK_DELETE_REQUESTED'
export const SMALL_TALK_DELETE_SUCCEEDED = 'SMALL_TALK_DELETE_SUCCEEDED'
export const SMALL_TALK_DELETE_ERROR = 'SMALL_TALK_DELETE_ERROR'
